//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation   {0} - {1}   has been added to {2}-{3} dictionary.
        /// </summary>
        public static string msgAddedItem {
            get {
                return ResourceManager.GetString("msgAddedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to language was added successfully!.
        /// </summary>
        public static string msgAddLenguage {
            get {
                return ResourceManager.GetString("msgAddLenguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention! It&apos;s important to consider the case of letters.
        /// </summary>
        public static string msgCaseLetters {
            get {
                return ResourceManager.GetString("msgCaseLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, choose one or more items for wordsuite.
        /// </summary>
        public static string msgChooseItems {
            get {
                return ResourceManager.GetString("msgChooseItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was created successfully!.
        /// </summary>
        public static string msgCreateUser {
            get {
                return ResourceManager.GetString("msgCreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item has been deleted.
        /// </summary>
        public static string msgDeletedItem {
            get {
                return ResourceManager.GetString("msgDeletedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to language was deleted successfully!.
        /// </summary>
        public static string msgDeleteLanguage {
            get {
                return ResourceManager.GetString("msgDeleteLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was deleted successfully!.
        /// </summary>
        public static string msgDeleteUser {
            get {
                return ResourceManager.GetString("msgDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;s profile was edited successfully!.
        /// </summary>
        public static string msgEditUser {
            get {
                return ResourceManager.GetString("msgEditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with such email is alredy exist.
        /// </summary>
        public static string msgEmailError {
            get {
                return ResourceManager.GetString("msgEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enforced delay between attempts.
        /// </summary>
        public static string msgEnforcedDelayBetweenAttempts {
            get {
                return ResourceManager.GetString("msgEnforcedDelayBetweenAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enforced number of attempts.
        /// </summary>
        public static string msgEnforcedNumberOfAttempts {
            get {
                return ResourceManager.GetString("msgEnforcedNumberOfAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request..
        /// </summary>
        public static string msgErrorMessage {
            get {
                return ResourceManager.GetString("msgErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords don&apos;t match.
        /// </summary>
        public static string msgErrorPassword {
            get {
                return ResourceManager.GetString("msgErrorPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To find students enter.
        /// </summary>
        public static string msgFindStudent {
            get {
                return ResourceManager.GetString("msgFindStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To find users enter.
        /// </summary>
        public static string msgFindUsers {
            get {
                return ResourceManager.GetString("msgFindUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter word you want to find.
        /// </summary>
        public static string msgFindWords {
            get {
                return ResourceManager.GetString("msgFindWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish tutorial.
        /// </summary>
        public static string msgFinishTutor {
            get {
                return ResourceManager.GetString("msgFinishTutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From now on:.
        /// </summary>
        public static string msgInfoAdvantages {
            get {
                return ResourceManager.GetString("msgInfoAdvantages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No need to make violence against yourself!.
        /// </summary>
        public static string msgInfoAdvantages_1 {
            get {
                return ResourceManager.GetString("msgInfoAdvantages_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more long lists hanging on walls, doors, mirrors!.
        /// </summary>
        public static string msgInfoAdvantages_2 {
            get {
                return ResourceManager.GetString("msgInfoAdvantages_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more stickers in your kitchen and bathroom!.
        /// </summary>
        public static string msgInfoAdvantages_3 {
            get {
                return ResourceManager.GetString("msgInfoAdvantages_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No need to remember which words you have already learnt and which ones you have not.
        /// </summary>
        public static string msgInfoAdvantages_4 {
            get {
                return ResourceManager.GetString("msgInfoAdvantages_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study words and have fun!.
        /// </summary>
        public static string msgInfoAdvantages_5 {
            get {
                return ResourceManager.GetString("msgInfoAdvantages_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to start, please register..
        /// </summary>
        public static string msgInfoAdvantages_6 {
            get {
                return ResourceManager.GetString("msgInfoAdvantages_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Happy WordLearning!!!.
        /// </summary>
        public static string msgInfoHappyWordLearn {
            get {
                return ResourceManager.GetString("msgInfoHappyWordLearn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello Friend!.
        /// </summary>
        public static string msgInfoHelloFriend {
            get {
                return ResourceManager.GetString("msgInfoHelloFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If so, this site is just for you!.
        /// </summary>
        public static string msgInfoItsForYou {
            get {
                return ResourceManager.GetString("msgInfoItsForYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studying a foreign language?.
        /// </summary>
        public static string msgInfoQuestions {
            get {
                return ResourceManager.GetString("msgInfoQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Having problems in studying a vocabulary?.
        /// </summary>
        public static string msgInfoQuestions_2 {
            get {
                return ResourceManager.GetString("msgInfoQuestions_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot make yourself study and repeat new words?.
        /// </summary>
        public static string msgInfoQuestions_3 {
            get {
                return ResourceManager.GetString("msgInfoQuestions_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wanna learn words just playing a game?.
        /// </summary>
        public static string msgInfoQuestions_4 {
            get {
                return ResourceManager.GetString("msgInfoQuestions_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WordLearn.
        /// </summary>
        public static string msgInfoWordLearn {
            get {
                return ResourceManager.GetString("msgInfoWordLearn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The WordLearn Team.
        /// </summary>
        public static string msgInfoWordLearnTeam {
            get {
                return ResourceManager.GetString("msgInfoWordLearnTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items have been added.
        /// </summary>
        public static string msgItemsAdded {
            get {
                return ResourceManager.GetString("msgItemsAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but translation  {0} - {1}  already exists in {2}-{3} dictionary.
        /// </summary>
        public static string msgNotAddedItem {
            get {
                return ResourceManager.GetString("msgNotAddedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item has not been deleted.
        /// </summary>
        public static string msgNotDeletedItem {
            get {
                return ResourceManager.GetString("msgNotDeletedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords don&apos;t match.
        /// </summary>
        public static string msgPasswordsontMatch {
            get {
                return ResourceManager.GetString("msgPasswordsontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has been removed successfully!.
        /// </summary>
        public static string msgRemoveCourse {
            get {
                return ResourceManager.GetString("msgRemoveCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is required..
        /// </summary>
        public static string msgRequiredField {
            get {
                return ResourceManager.GetString("msgRequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password was reseted successfully!.
        /// </summary>
        public static string msgResetPassword {
            get {
                return ResourceManager.GetString("msgResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello Guest! You can:.
        /// </summary>
        public static string msgToGuest {
            get {
                return ResourceManager.GetString("msgToGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To see wordsuites select language.
        /// </summary>
        public static string msgToSeeWordsuites {
            get {
                return ResourceManager.GetString("msgToSeeWordsuites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translations from this file already exist or file has wrong format or you didn&apos;t choose a file.
        /// </summary>
        public static string msgTranslationsExist {
            get {
                return ResourceManager.GetString("msgTranslationsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can try to pass Quiz again at:.
        /// </summary>
        public static string msgTryPassAgain {
            get {
                return ResourceManager.GetString("msgTryPassAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncorrect email.
        /// </summary>
        public static string msgUncorrectEmail {
            get {
                return ResourceManager.GetString("msgUncorrectEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect username .Username can contain only _  or latin characters or digits.The length of username must be between 6 and 15 characters.
        /// </summary>
        public static string msgUncorrectLogin {
            get {
                return ResourceManager.GetString("msgUncorrectLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid number.
        ///    Valid format: 000-000-00-00
        ///    .
        /// </summary>
        public static string msgUncorrectPhoneNumber {
            get {
                return ResourceManager.GetString("msgUncorrectPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz settings was updated successfully!.
        /// </summary>
        public static string msgUpdateSetting {
            get {
                return ResourceManager.GetString("msgUpdateSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with such email is alredy exist.
        /// </summary>
        public static string msgUserEmail {
            get {
                return ResourceManager.GetString("msgUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with such user name is alredy exist.
        /// </summary>
        public static string msgUserName {
            get {
                return ResourceManager.GetString("msgUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with such name is alredy exist.
        /// </summary>
        public static string msgUserNameExist {
            get {
                return ResourceManager.GetString("msgUserNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wordsuite name is required.
        /// </summary>
        public static string msgWordsuiteIsRequired {
            get {
                return ResourceManager.GetString("msgWordsuiteIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string RegisterModel_UserName_Login {
            get {
                return ResourceManager.GetString("RegisterModel_UserName_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string s {
            get {
                return ResourceManager.GetString("s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your username and password.
        /// </summary>
        public static string txt {
            get {
                return ResourceManager.GetString("txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string txtAction {
            get {
                return ResourceManager.GetString("txtAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string txtAdd {
            get {
                return ResourceManager.GetString("txtAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add checked items.
        /// </summary>
        public static string txtAddCheckedItems {
            get {
                return ResourceManager.GetString("txtAddCheckedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Item.
        /// </summary>
        public static string txtAddItem {
            get {
                return ResourceManager.GetString("txtAddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Item.
        /// </summary>
        public static string txtAddItemForm {
            get {
                return ResourceManager.GetString("txtAddItemForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Items.
        /// </summary>
        public static string txtAddItems {
            get {
                return ResourceManager.GetString("txtAddItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Items To Wordsuite.
        /// </summary>
        public static string txtAddItemsWordsuite {
            get {
                return ResourceManager.GetString("txtAddItemsWordsuite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Language.
        /// </summary>
        public static string txtAddLanguage {
            get {
                return ResourceManager.GetString("txtAddLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add one more translation.
        /// </summary>
        public static string txtAddMoreTransl {
            get {
                return ResourceManager.GetString("txtAddMoreTransl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new translations.
        /// </summary>
        public static string txtAddNewTransl {
            get {
                return ResourceManager.GetString("txtAddNewTransl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Course.
        /// </summary>
        public static string txtAddToCourse {
            get {
                return ResourceManager.GetString("txtAddToCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Wordsuite.
        /// </summary>
        public static string txtAddToWordsuite {
            get {
                return ResourceManager.GetString("txtAddToWordsuite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add WordSuite.
        /// </summary>
        public static string txtAddWordSuite {
            get {
                return ResourceManager.GetString("txtAddWordSuite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Page.
        /// </summary>
        public static string txtAdminPage {
            get {
                return ResourceManager.GetString("txtAdminPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All courses.
        /// </summary>
        public static string txtAllCourses {
            get {
                return ResourceManager.GetString("txtAllCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Dictionary.
        /// </summary>
        public static string txtAllDictionary {
            get {
                return ResourceManager.GetString("txtAllDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All WordSuites.
        /// </summary>
        public static string txtAllWordSuites {
            get {
                return ResourceManager.GetString("txtAllWordSuites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer is correct.
        /// </summary>
        public static string txtAnswerIsCorrect {
            get {
                return ResourceManager.GetString("txtAnswerIsCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign course.
        /// </summary>
        public static string txtAssignCourse {
            get {
                return ResourceManager.GetString("txtAssignCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign courses.
        /// </summary>
        public static string txtAssignCourses {
            get {
                return ResourceManager.GetString("txtAssignCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignments.
        /// </summary>
        public static string txtAssignments {
            get {
                return ResourceManager.GetString("txtAssignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign teacher.
        /// </summary>
        public static string txtAssignTeacher {
            get {
                return ResourceManager.GetString("txtAssignTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string txtBack {
            get {
                return ResourceManager.GetString("txtBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse File....
        /// </summary>
        public static string txtBrowseButton {
            get {
                return ResourceManager.GetString("txtBrowseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string txtCancel {
            get {
                return ResourceManager.GetString("txtCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string txtChange {
            get {
                return ResourceManager.GetString("txtChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change teacher.
        /// </summary>
        public static string txtChangeTeacher {
            get {
                return ResourceManager.GetString("txtChangeTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose gender.
        /// </summary>
        public static string txtChooseGender {
            get {
                return ResourceManager.GetString("txtChooseGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose role.
        /// </summary>
        public static string txtChooseRole {
            get {
                return ResourceManager.GetString("txtChooseRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string txtClose {
            get {
                return ResourceManager.GetString("txtClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string txtConfirm {
            get {
                return ResourceManager.GetString("txtConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string txtConfirmPassword {
            get {
                return ResourceManager.GetString("txtConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - SoftServe Lv-102.Net.
        /// </summary>
        public static string txtCopyrights {
            get {
                return ResourceManager.GetString("txtCopyrights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course.
        /// </summary>
        public static string txtCourse {
            get {
                return ResourceManager.GetString("txtCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course language.
        /// </summary>
        public static string txtCourseLanguage {
            get {
                return ResourceManager.GetString("txtCourseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses.
        /// </summary>
        public static string txtCourses {
            get {
                return ResourceManager.GetString("txtCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course wordsuites.
        /// </summary>
        public static string txtCourseWordsuites {
            get {
                return ResourceManager.GetString("txtCourseWordsuites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create course.
        /// </summary>
        public static string txtCreateCourse {
            get {
                return ResourceManager.GetString("txtCreateCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new course.
        /// </summary>
        public static string txtCreateNewCourse {
            get {
                return ResourceManager.GetString("txtCreateNewCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User.
        /// </summary>
        public static string txtCreateUser {
            get {
                return ResourceManager.GetString("txtCreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create WordSuite.
        /// </summary>
        public static string txtCreateWordSuite {
            get {
                return ResourceManager.GetString("txtCreateWordSuite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator.
        /// </summary>
        public static string txtCreator {
            get {
                return ResourceManager.GetString("txtCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curtailment.
        /// </summary>
        public static string txtCurtailment {
            get {
                return ResourceManager.GetString("txtCurtailment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        public static string txtDateOfBirthday {
            get {
                return ResourceManager.GetString("txtDateOfBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string txtDelete {
            get {
                return ResourceManager.GetString("txtDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary.
        /// </summary>
        public static string txtDictionary {
            get {
                return ResourceManager.GetString("txtDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Sample.
        /// </summary>
        public static string txtDownloadButton {
            get {
                return ResourceManager.GetString("txtDownloadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string txtEdit {
            get {
                return ResourceManager.GetString("txtEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile Page.
        /// </summary>
        public static string txtEditProfilePage {
            get {
                return ResourceManager.GetString("txtEditProfilePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string txtEmail {
            get {
                return ResourceManager.GetString("txtEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Enter Data.
        /// </summary>
        public static string txtEnterData {
            get {
                return ResourceManager.GetString("txtEnterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error..
        /// </summary>
        public static string txtError {
            get {
                return ResourceManager.GetString("txtError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string txtFemale {
            get {
                return ResourceManager.GetString("txtFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string txtFirstName {
            get {
                return ResourceManager.GetString("txtFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest.
        /// </summary>
        public static string txtGuest {
            get {
                return ResourceManager.GetString("txtGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string txtHideButton {
            get {
                return ResourceManager.GetString("txtHideButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string txtHome {
            get {
                return ResourceManager.GetString("txtHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from file.
        /// </summary>
        public static string txtImportButton {
            get {
                return ResourceManager.GetString("txtImportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported Items From File.
        /// </summary>
        public static string txtImportedItems {
            get {
                return ResourceManager.GetString("txtImportedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Items From File.
        /// </summary>
        public static string txtImportFromFile {
            get {
                return ResourceManager.GetString("txtImportFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string txtInitOriginalLanguage {
            get {
                return ResourceManager.GetString("txtInitOriginalLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukrainian.
        /// </summary>
        public static string txtInitTranslationLanguage {
            get {
                return ResourceManager.GetString("txtInitTranslationLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string txtItem {
            get {
                return ResourceManager.GetString("txtItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string txtItems {
            get {
                return ResourceManager.GetString("txtItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string txtLanguage {
            get {
                return ResourceManager.GetString("txtLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string txtLanguages {
            get {
                return ResourceManager.GetString("txtLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string txtLastName {
            get {
                return ResourceManager.GetString("txtLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learned date.
        /// </summary>
        public static string txtLearnedDate {
            get {
                return ResourceManager.GetString("txtLearnedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string txtLogin {
            get {
                return ResourceManager.GetString("txtLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string txtLogOut {
            get {
                return ResourceManager.GetString("txtLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string txtMale {
            get {
                return ResourceManager.GetString("txtMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        public static string txtManager {
            get {
                return ResourceManager.GetString("txtManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multilingual.
        /// </summary>
        public static string txtMultilingual {
            get {
                return ResourceManager.GetString("txtMultilingual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My courses.
        /// </summary>
        public static string txtMyCourses {
            get {
                return ResourceManager.GetString("txtMyCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Students.
        /// </summary>
        public static string txtMyStudents {
            get {
                return ResourceManager.GetString("txtMyStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Work.
        /// </summary>
        public static string txtMyWork {
            get {
                return ResourceManager.GetString("txtMyWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string txtName {
            get {
                return ResourceManager.GetString("txtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string txtNext {
            get {
                return ResourceManager.GetString("txtNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next page.
        /// </summary>
        public static string txtNextPage {
            get {
                return ResourceManager.GetString("txtNextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string txtNone {
            get {
                return ResourceManager.GetString("txtNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string txtOk {
            get {
                return ResourceManager.GetString("txtOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string txtOr {
            get {
                return ResourceManager.GetString("txtOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Language.
        /// </summary>
        public static string txtOriginalLanguage {
            get {
                return ResourceManager.GetString("txtOriginalLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Word.
        /// </summary>
        public static string txtOriginalWord {
            get {
                return ResourceManager.GetString("txtOriginalWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part of speech.
        /// </summary>
        public static string txtPartOfSpeech {
            get {
                return ResourceManager.GetString("txtPartOfSpeech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string txtPassword {
            get {
                return ResourceManager.GetString("txtPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person Role.
        /// </summary>
        public static string txtPersonRole {
            get {
                return ResourceManager.GetString("txtPersonRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string txtPhoneNumber {
            get {
                return ResourceManager.GetString("txtPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string txtPrevious {
            get {
                return ResourceManager.GetString("txtPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous page.
        /// </summary>
        public static string txtPreviousPage {
            get {
                return ResourceManager.GetString("txtPreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print table.
        /// </summary>
        public static string txtPrintTable {
            get {
                return ResourceManager.GetString("txtPrintTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Course WordSuites.
        /// </summary>
        public static string txtPrivateCourseWordSuites {
            get {
                return ResourceManager.GetString("txtPrivateCourseWordSuites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private course wordsuites.
        /// </summary>
        public static string txtPrivateCourseWS {
            get {
                return ResourceManager.GetString("txtPrivateCourseWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string txtProgress {
            get {
                return ResourceManager.GetString("txtProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz.
        /// </summary>
        public static string txtQuiz {
            get {
                return ResourceManager.GetString("txtQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz Answers.
        /// </summary>
        public static string txtQuizAnswers {
            get {
                return ResourceManager.GetString("txtQuizAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz timeout.
        /// </summary>
        public static string txtQuizTimeOut {
            get {
                return ResourceManager.GetString("txtQuizTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string txtRegister {
            get {
                return ResourceManager.GetString("txtRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered users.
        /// </summary>
        public static string txtRegisteredUsers {
            get {
                return ResourceManager.GetString("txtRegisteredUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Page.
        /// </summary>
        public static string txtRegisterPage {
            get {
                return ResourceManager.GetString("txtRegisterPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string txtRememberMe {
            get {
                return ResourceManager.GetString("txtRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string txtRemove {
            get {
                return ResourceManager.GetString("txtRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string txtRename {
            get {
                return ResourceManager.GetString("txtRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename WordSuite.
        /// </summary>
        public static string txtRenameWordSuite {
            get {
                return ResourceManager.GetString("txtRenameWordSuite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password *.
        /// </summary>
        public static string txtRequiredConfirmPassword {
            get {
                return ResourceManager.GetString("txtRequiredConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail *.
        /// </summary>
        public static string txtRequiredEmail {
            get {
                return ResourceManager.GetString("txtRequiredEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name *.
        /// </summary>
        public static string txtRequiredFirstName {
            get {
                return ResourceManager.GetString("txtRequiredFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name *.
        /// </summary>
        public static string txtRequiredLastName {
            get {
                return ResourceManager.GetString("txtRequiredLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login *.
        /// </summary>
        public static string txtRequiredLogin {
            get {
                return ResourceManager.GetString("txtRequiredLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password *.
        /// </summary>
        public static string txtRequiredPassword {
            get {
                return ResourceManager.GetString("txtRequiredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string txtResetPassword {
            get {
                return ResourceManager.GetString("txtResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Translation.
        /// </summary>
        public static string txtRightTranslation {
            get {
                return ResourceManager.GetString("txtRightTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run quiz.
        /// </summary>
        public static string txtRunQuiz {
            get {
                return ResourceManager.GetString("txtRunQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run tutorial.
        /// </summary>
        public static string txtRunTutorial {
            get {
                return ResourceManager.GetString("txtRunTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample.txt.
        /// </summary>
        public static string txtSampleFileName {
            get {
                return ResourceManager.GetString("txtSampleFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string txtSave {
            get {
                return ResourceManager.GetString("txtSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string txtSearch {
            get {
                return ResourceManager.GetString("txtSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by tags.
        /// </summary>
        public static string txtSearchByTags {
            get {
                return ResourceManager.GetString("txtSearchByTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by word.
        /// </summary>
        public static string txtSearchByWords {
            get {
                return ResourceManager.GetString("txtSearchByWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мy words.
        /// </summary>
        public static string txtSearchOnlyOwnWords {
            get {
                return ResourceManager.GetString("txtSearchOnlyOwnWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search a word....
        /// </summary>
        public static string txtSearchWord {
            get {
                return ResourceManager.GetString("txtSearchWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Words.
        /// </summary>
        public static string txtSearchWords {
            get {
                return ResourceManager.GetString("txtSearchWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a language.
        /// </summary>
        public static string txtSelectLanguage {
            get {
                return ResourceManager.GetString("txtSelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a part of speech.
        /// </summary>
        public static string txtSelectPartOfSpeech {
            get {
                return ResourceManager.GetString("txtSelectPartOfSpeech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string txtSettings {
            get {
                return ResourceManager.GetString("txtSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        public static string txtSex {
            get {
                return ResourceManager.GetString("txtSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show WordSuites.
        /// </summary>
        public static string txtShowWordSuites {
            get {
                return ResourceManager.GetString("txtShowWordSuites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string txtSignIn {
            get {
                return ResourceManager.GetString("txtSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string txtStatus {
            get {
                return ResourceManager.GetString("txtStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string txtStop {
            get {
                return ResourceManager.GetString("txtStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        public static string txtStudent {
            get {
                return ResourceManager.GetString("txtStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student courses.
        /// </summary>
        public static string txtStudentCourses {
            get {
                return ResourceManager.GetString("txtStudentCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students.
        /// </summary>
        public static string txtStudents {
            get {
                return ResourceManager.GetString("txtStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string txtTags {
            get {
                return ResourceManager.GetString("txtTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher.
        /// </summary>
        public static string txtTeacher {
            get {
                return ResourceManager.GetString("txtTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teachers.
        /// </summary>
        public static string txtTeachers {
            get {
                return ResourceManager.GetString("txtTeachers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To all courses.
        /// </summary>
        public static string txtToAllCourses {
            get {
                return ResourceManager.GetString("txtToAllCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To create new course.
        /// </summary>
        public static string txtToCreateNewCourse {
            get {
                return ResourceManager.GetString("txtToCreateNewCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To create new Wordsuite.
        /// </summary>
        public static string txtToCreateWS {
            get {
                return ResourceManager.GetString("txtToCreateWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcription.
        /// </summary>
        public static string txtTranscription {
            get {
                return ResourceManager.GetString("txtTranscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation.
        /// </summary>
        public static string txtTranslation {
            get {
                return ResourceManager.GetString("txtTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation Language.
        /// </summary>
        public static string txtTranslationLanguage {
            get {
                return ResourceManager.GetString("txtTranslationLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation Word.
        /// </summary>
        public static string txtTranslationWord {
            get {
                return ResourceManager.GetString("txtTranslationWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string txtUser {
            get {
                return ResourceManager.GetString("txtUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Translation.
        /// </summary>
        public static string txtUserTranslation {
            get {
                return ResourceManager.GetString("txtUserTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbatim.
        /// </summary>
        public static string txtVerbatim {
            get {
                return ResourceManager.GetString("txtVerbatim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View courses.
        /// </summary>
        public static string txtViewCourses {
            get {
                return ResourceManager.GetString("txtViewCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Items.
        /// </summary>
        public static string txtViewItems {
            get {
                return ResourceManager.GetString("txtViewItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View WordSuites.
        /// </summary>
        public static string txtViewWordSuites {
            get {
                return ResourceManager.GetString("txtViewWordSuites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string txtVocabularies {
            get {
                return ResourceManager.GetString("txtVocabularies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word.
        /// </summary>
        public static string txtWord {
            get {
                return ResourceManager.GetString("txtWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WordSuite.
        /// </summary>
        public static string txtWordSuite {
            get {
                return ResourceManager.GetString("txtWordSuite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wordsuite Language.
        /// </summary>
        public static string txtWordsuitelanguage {
            get {
                return ResourceManager.GetString("txtWordsuitelanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wordsuite Name.
        /// </summary>
        public static string txtWordsuiteName {
            get {
                return ResourceManager.GetString("txtWordsuiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WordSuites.
        /// </summary>
        public static string txtWordSuites {
            get {
                return ResourceManager.GetString("txtWordSuites", resourceCulture);
            }
        }
    }
}
