//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace generatorDB.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("generatorDB.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abacus	=	абак(а)	
        ///abacus	=	координатна сітка	
        ///abacus	=	номограма	
        ///abacus	=	рахівниця	
        ///abandon	=	відкидати	
        ///abandon	=	відкинути	
        ///abandon	=	відмовитися	
        ///abandon	=	відмовлятися	
        ///abandon	=	полишати	
        ///abandon	=	припиняти	
        ///abandon	=	скасовувати	
        ///abandon	=	скасувати	
        ///abandoned event	=	відкинена (відхилена) подія	
        ///abase	=	понижувати	
        ///abase	=	понизити (в посаді)	
        ///abase	=	принижувати	
        ///abase	=	принизити	
        ///abate	=	зменшувати(ся)	
        ///abate	=	послаблювати(ся)	
        ///abate	=	скасовувати (юрид.)	
        ///abbreviate	=	вкор [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dictionary_Eng_Ukr {
            get {
                return ResourceManager.GetString("dictionary_Eng_Ukr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maria Anders
        ///Ana Trujillo
        ///Antonio Moreno
        ///Thomas Hardy
        ///Christina Berglund
        ///Hanna Moos
        ///Frederique Citeaux
        ///Martin Sommer
        ///Laurence Lebihan
        ///Elizabeth Lincoln
        ///Victoria Ashworth
        ///Patricio Simpson
        ///Francisco Chang
        ///Yang Wang
        ///Pedro Afonso
        ///Elizabeth Brown
        ///Sven Ottlieb
        ///Janine Labrune
        ///Ann Devon
        ///Roland Mendel
        ///Aria Cruz
        ///Diego Roel
        ///Martine Rance
        ///Maria Larsson
        ///Peter Franken
        ///Carine Schmitt
        ///Paolo Accorti
        ///Lino Rodriguez
        ///Eduardo Saavedra
        ///Pedro Freyre
        ///Andre Fonseca
        ///Howard Snyder
        ///Manuel Pereira
        ///Mario [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Names {
            get {
                return ResourceManager.GetString("Names", resourceCulture);
            }
        }
    }
}
